# --- Sample dataset

# --- !Ups

insert into college (id, name, st, web_address) values ( 6121, 'Creighton University', 'Nebraska', 'http://www.gocreighton.com');
insert into college (id, name, st, web_address) values ( 6877, 'University of Nebraska-Lincoln', 'Nebraska', 'http://www.huskers.com');
insert into college (id, name, st, web_address) values ( 6420, 'University of Nebraska-Omaha', 'Nebraska', 'http://www.omavs.com');
insert into college (id, name, st, web_address) values ( 6466, 'Chadron State College', 'Nebraska', 'http://www.chadroneagles.com');
insert into college (id, name, st, web_address) values ( 6467, 'University of Nebraska-Kearney', 'Nebraska', 'http://www.lopers.com');
insert into college (id, name, st, web_address) values ( 6469, 'Wayne State College', 'Nebraska', 'http://www.wscwildcats.com');
insert into college (id, name, st, web_address) values ( 6470, 'Nebraska Wesleyan University', 'Nebraska', 'http://www.nwusports.com');
insert into college (id, name, st, web_address) values ( 6053, 'Bellevue University', 'Nebraska', 'http://www.bubruins.com');
insert into college (id, name, st, web_address) values ( 6116, 'Concordia University', 'Nebraska', 'http://www.cune.edu/athletics');
insert into college (id, name, st, web_address) values ( 6165, 'Doane College', 'Nebraska', 'http://www.doaneathletics.com');
insert into college (id, name, st, web_address) values ( 6270, 'Hastings College', 'Nebraska', 'http://www.hastingsbroncos.com');
insert into college (id, name, st, web_address) values ( 6406, 'Midland University', 'Nebraska', 'http://www.midlandathletics.com');
insert into college (id, name, st, web_address) values ( 6468, 'Peru State College', 'Nebraska', 'http://www.pscbobcats.com');
insert into college (id, name, st, web_address) values ( 6106, 'College of Saint Mary', 'Nebraska', 'http://www.csmflames.com');
insert into college (id, name, st, web_address) values ( 6984, 'York College', 'Nebraska', 'http://www.ycpanthers.com');


insert into sport (sportid, sportname, division, college_id, prospectform) values (6, 'Men''s Golf', 'NAIA', 6053, 'http://bubruins.com/sports/mgolf/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (18, 'Men''s Basketball', 'NAIA', 6053, 'http://bubruins.com/sports/mbkb/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (31, 'Baseball', 'NAIA', 6053, 'http://bubruins.com/sports/bsb/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (52, 'Men''s Soccer', 'NAIA', 6053, 'http://bubruins.com/sports/msoc/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (135, 'Women''s Golf', 'NAIA', 6053, 'http://bubruins.com/sports/wgolf/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (142, 'Women''s Soccer', 'NAIA', 6053, 'http://bubruins.com/sports/wsoc/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (156, 'Softball', 'NAIA', 6053, 'http://bubruins.com/sports/sball/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (181, 'Volleyball', 'NAIA', 6053, 'http://bubruins.com/sports/wvball/Questionnaire');
insert into sport (sportid, sportname, division, college_id, prospectform) values (1, 'Men''s Golf', 'Division 1', 6121, 'null');


insert into college (id, name, st, web_address) values ( 6121, 'Creighton University', 'Nebraska', 'http://www.creighton.edu');
insert into college (id, name, st, web_address) values ( 6877, 'University of Nebraska-Lincoln', 'Nebraska', 'http://www.unl.edu');
insert into college (id, name, st, web_address) values ( 6420, 'University of Nebraska-Omaha', 'Nebraska', 'http://www.unomaha.edu');
insert into college (id, name, st, web_address) values ( 6466, 'Chadron State College', 'Nebraska', 'http://www.csc.edu');
insert into college (id, name, st, web_address) values ( 6467, 'University of Nebraska-Kearney', 'Nebraska', 'http://www.unk.edu');
insert into college (id, name, st, web_address) values ( 6469, 'Wayne State College', 'Nebraska', 'http://www.wsc.edu');
insert into college (id, name, st, web_address) values ( 6470, 'Nebraska Wesleyan University', 'Nebraska', 'http://www.nebrwesleyan.edu');
insert into college (id, name, st, web_address) values ( 6053, 'Bellevue University', 'Nebraska', 'http://www.bellevue.edu');
insert into college (id, name, st, web_address) values ( 6116, 'Concordia University', 'Nebraska', 'http://www.cune.edu');
insert into college (id, name, st, web_address) values ( 6165, 'Doane College', 'Nebraska', 'http://www.doane.edu');
insert into college (id, name, st, web_address) values ( 6270, 'Hastings College', 'Nebraska', 'http://www.hastings.edu');
insert into college (id, name, st, web_address) values ( 6406, 'Midland University', 'Nebraska', 'http://www.midlandu.edu');
insert into college (id, name, st, web_address) values ( 6468, 'Peru State College', 'Nebraska', 'http://www.peru.edu');
insert into college (id, name, st, web_address) values ( 6106, 'College of Saint Mary', 'Nebraska', 'http://www.csm.edu');
insert into college (id, name, st, web_address) values ( 6984, 'York College', 'Nebraska', 'http://www.york.edu');

insert into sport (sportid, sportname, division, college_id) values (1, 'Men''s Golf', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (2, 'Men''s Golf', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (3, 'Men''s Golf', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (4, 'Men''s Golf', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (5, 'Men''s Golf', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (6, 'Men''s Golf', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (7, 'Men''s Golf', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (8, 'Men''s Golf', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (9, 'Men''s Golf', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (10, 'Men''s Golf', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (11, 'Men''s Basketball', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (12, 'Men''s Basketball', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (13, 'Men''s Basketball', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (14, 'Men''s Basketball', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (15, 'Men''s Basketball', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (16, 'Men''s Basketball', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (17, 'Men''s Basketball', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (18, 'Men''s Basketball', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (19, 'Men''s Basketball', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (20, 'Men''s Basketball', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (21, 'Men''s Basketball', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (22, 'Men''s Basketball', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (23, 'Men''s Basketball', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (24, 'Men''s Basketball', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (25, 'Baseball', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (26, 'Baseball', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (27, 'Baseball', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (28, 'Baseball', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (29, 'Baseball', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (30, 'Baseball', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (31, 'Baseball', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (32, 'Baseball', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (33, 'Baseball', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (34, 'Baseball', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (35, 'Baseball', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (36, 'Baseball', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (37, 'Baseball', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (38, 'Men''s Cross Country', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (39, 'Men''s Cross Country', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (40, 'Men''s Cross Country', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (41, 'Men''s Cross Country', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (42, 'Men''s Cross Country', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (43, 'Men''s Cross Country', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (44, 'Men''s Cross Country', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (45, 'Men''s Cross Country', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (46, 'Men''s Cross Country', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (47, 'Men''s Cross Country', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (48, 'Men''s Cross Country', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (49, 'Men''s Soccer', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (50, 'Men''s Soccer', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (51, 'Men''s Soccer', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (52, 'Men''s Soccer', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (53, 'Men''s Soccer', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (54, 'Men''s Soccer', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (55, 'Men''s Soccer', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (56, 'Men''s Soccer', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (57, 'Men''s Soccer', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (58, 'Men''s Tennis', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (59, 'Men''s Tennis', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (60, 'Men''s Tennis', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (61, 'Men''s Tennis', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (62, 'Men''s Tennis', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (63, 'Men''s Tennis', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (64, 'Men''s Tennis', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (65, 'Men''s Tennis', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (66, 'Men''s Tennis', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (68, 'Football', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (67, 'Football', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (69, 'Football', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (70, 'Football', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (71, 'Football', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (72, 'Football', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (73, 'Football', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (74, 'Football', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (75, 'Football', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (76, 'Football', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (77, 'Wrestling', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (78, 'Wrestling', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (79, 'Wrestling', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (80, 'Wrestling', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (81, 'Wrestling', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (82, 'Wrestling', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (83, 'Wrestling', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (84, 'Wrestling', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (85, 'Men''s Track and Field', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (86, 'Men''s Track and Field', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (87, 'Men''s Track and Field', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (88, 'Men''s Track and Field', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (89, 'Men''s Track and Field', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (90, 'Men''s Track and Field', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (91, 'Men''s Track and Field', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (92, 'Men''s Track and Field', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (93, 'Men''s Track and Field', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (94, 'Men''s Track and Field', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (95, 'Women''s Basketball', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (96, 'Women''s Basketball', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (97, 'Women''s Basketball', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (98, 'Women''s Basketball', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (99, 'Women''s Basketball', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (100, 'Women''s Basketball', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (101, 'Women''s Basketball', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (102, 'Women''s Basketball', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (103, 'Women''s Basketball', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (104, 'Women''s Basketball', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (105, 'Women''s Basketball', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (106, 'Women''s Basketball', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (107, 'Women''s Basketball', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (108, 'Women''s Basketball', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (109, 'Women''s Cross Country', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (110, 'Women''s Cross Country', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (111, 'Women''s Cross Country', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (112, 'Women''s Cross Country', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (113, 'Women''s Cross Country', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (114, 'Women''s Cross Country', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (115, 'Women''s Cross Country', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (116, 'Women''s Cross Country', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (117, 'Women''s Cross Country', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (118, 'Women''s Cross Country', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (119, 'Women''s Cross Country', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (120, 'Women''s Cross Country', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (121, 'Women''s Cross Country', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (122, 'Women''s Cross Country', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (123, 'Women''s Golf', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (124, 'Women''s Golf', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (125, 'Women''s Golf', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (126, 'Women''s Golf', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (127, 'Women''s Golf', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (128, 'Women''s Golf', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (129, 'Women''s Golf', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (130, 'Women''s Golf', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (131, 'Women''s Golf', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (132, 'Women''s Golf', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (133, 'Women''s Golf', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (134, 'Women''s Golf', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (135, 'Women''s Golf', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (136, 'Women''s Soccer', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (137, 'Women''s Soccer', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (138, 'Women''s Soccer', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (139, 'Women''s Soccer', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (140, 'Women''s Soccer', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (141, 'Women''s Soccer', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (142, 'Women''s Soccer', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (143, 'Women''s Soccer', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (144, 'Women''s Soccer', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (145, 'Women''s Soccer', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (146, 'Women''s Soccer', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (147, 'Women''s Soccer', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (148, 'Women''s Soccer', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (149, 'Softball', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (150, 'Softball', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (151, 'Softball', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (152, 'Softball', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (153, 'Softball', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (154, 'Softball', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (155, 'Softball', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (156, 'Softball', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (157, 'Softball', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (158, 'Softball', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (159, 'Softball', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (160, 'Softball', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (161, 'Softball', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (162, 'Softball', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (163, 'Softball', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (164, 'Women''s Tennis', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (165, 'Women''s Tennis', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (166, 'Women''s Tennis', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (167, 'Women''s Tennis', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (168, 'Women''s Tennis', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (169, 'Women''s Tennis', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (170, 'Women''s Tennis', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (171, 'Women''s Tennis', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (172, 'Women''s Tennis', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (173, 'Women''s Tennis', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (174, 'Volleyball', 'Division 1', 6121);
insert into sport (sportid, sportname, division, college_id) values (175, 'Volleyball', 'Division 1', 6877);
insert into sport (sportid, sportname, division, college_id) values (176, 'Volleyball', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (177, 'Volleyball', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (178, 'Volleyball', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (179, 'Volleyball', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (180, 'Volleyball', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (181, 'Volleyball', 'NAIA', 6053);
insert into sport (sportid, sportname, division, college_id) values (182, 'Volleyball', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (183, 'Volleyball', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (184, 'Volleyball', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (185, 'Volleyball', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (186, 'Volleyball', 'NAIA', 6468);
insert into sport (sportid, sportname, division, college_id) values (187, 'Volleyball', 'NAIA', 6106);
insert into sport (sportid, sportname, division, college_id) values (188, 'Volleyball', 'NAIA', 6984);
insert into sport (sportid, sportname, division, college_id) values (189, 'Women''s Track and Field', 'Division 1', 6420);
insert into sport (sportid, sportname, division, college_id) values (190, 'Women''s Track and Field', 'Division 2', 6466);
insert into sport (sportid, sportname, division, college_id) values (191, 'Women''s Track and Field', 'Division 2', 6467);
insert into sport (sportid, sportname, division, college_id) values (192, 'Women''s Track and Field', 'Division 2', 6469);
insert into sport (sportid, sportname, division, college_id) values (193, 'Women''s Track and Field', 'Division 3', 6470);
insert into sport (sportid, sportname, division, college_id) values (194, 'Women''s Track and Field', 'NAIA', 6116);
insert into sport (sportid, sportname, division, college_id) values (195, 'Women''s Track and Field', 'NAIA', 6165);
insert into sport (sportid, sportname, division, college_id) values (196, 'Women''s Track and Field', 'NAIA', 6270);
insert into sport (sportid, sportname, division, college_id) values (197, 'Women''s Track and Field', 'NAIA', 6406);
insert into sport (sportid, sportname, division, college_id) values (198, 'Women''s Track and Field', 'NAIA', 6984);

# --- !Downs

delete from college;
delete from sport;