# --- Sample dataset

# --- !Ups

insert into college (id, name, st, web_address) values ( 6121, 'Creighton University', 'Nebraska', 'http://www.gocreighton.com');
insert into college (id, name, st, web_address) values ( 6877, 'University of Nebraska-Lincoln', 'Nebraska', 'http://www.huskers.com');
insert into college (id, name, st, web_address) values ( 6420, 'University of Nebraska-Omaha', 'Nebraska', 'http://www.omavs.com');
insert into college (id, name, st, web_address) values ( 6466, 'Chadron State College', 'Nebraska', 'http://www.chadroneagles.com');
insert into college (id, name, st, web_address) values ( 6467, 'University of Nebraska-Kearney', 'Nebraska', 'http://www.lopers.com');
insert into college (id, name, st, web_address) values ( 6469, 'Wayne State College', 'Nebraska', 'http://www.wscwildcats.com');
insert into college (id, name, st, web_address) values ( 6470, 'Nebraska Wesleyan University', 'Nebraska', 'http://www.nwusports.com');
insert into college (id, name, st, web_address) values ( 6053, 'Bellevue University', 'Nebraska', 'http://www.bubruins.com');
insert into college (id, name, st, web_address) values ( 6116, 'Concordia University', 'Nebraska', 'http://www.cune.edu/athletics');
insert into college (id, name, st, web_address) values ( 6165, 'Doane College', 'Nebraska', 'http://www.doaneathletics.com');
insert into college (id, name, st, web_address) values ( 6270, 'Hastings College', 'Nebraska', 'http://www.hastingsbroncos.com');
insert into college (id, name, st, web_address) values ( 6406, 'Midland University', 'Nebraska', 'http://www.midlandathletics.com');
insert into college (id, name, st, web_address) values ( 6468, 'Peru State College', 'Nebraska', 'http://www.pscbobcats.com');
insert into college (id, name, st, web_address) values ( 6106, 'College of Saint Mary', 'Nebraska', 'http://www.csmflames.com');
insert into college (id, name, st, web_address) values ( 6984, 'York College', 'Nebraska', 'http://www.ycpanthers.com');
insert into college (id, name, st, web_address) values ( 3965, 'Williams College', 'Massachusetts', 'http://athletics.williams.edu/');


insert into sport (sportid, sportname, division, college_id, prospectform) values (6, 'Men''s Golf', 'NAIA', 6053, 'http://bubruins.com/sports/mgolf/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (18, 'Men''s Basketball', 'NAIA', 6053, 'http://bubruins.com/sports/mbkb/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (31, 'Baseball', 'NAIA', 6053, 'http://bubruins.com/sports/bsb/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (52, 'Men''s Soccer', 'NAIA', 6053, 'http://bubruins.com/sports/msoc/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (135, 'Women''s Golf', 'NAIA', 6053, 'http://bubruins.com/sports/wgolf/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (142, 'Women''s Soccer', 'NAIA', 6053, 'http://bubruins.com/sports/wsoc/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (156, 'Softball', 'NAIA', 6053, 'http://bubruins.com/sports/sball/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (181, 'Volleyball', 'NAIA', 6053, 'http://bubruins.com/sports/wvball/Questionnaire');
insert into sport (sportid, sportname, division, college_id, prospectform) values (1, 'Men''s Golf', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2377&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (11, 'Men''s Basketball', 'Division 1', 6121, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (25, 'Baseball', 'Division 1', 6121, 'https://www.frontrush.com/FR_Web_App/Player/PlayerSubmit.aspx?DB_OEM_ID=1000&sid=5059&ptype=recruit');
insert into sport (sportid, sportname, division, college_id, prospectform) values (38, 'Men''s Cross Country', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2375&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (109, 'Women''s Cross Country', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2376&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (58, 'Men''s Tennis', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2384&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (164, 'Women''s Tennis', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2385&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (149, 'Softball', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2381&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (123, 'Women''s Golf', 'Division 1', 6121, 'http://www.gocreighton.com//quest/Questionaire.dbml?QID=2378&DB_OEM_ID=1000&DB_OEM_ID=1000');
insert into sport (sportid, sportname, division, college_id, prospectform) values (49, 'Men''s Soccer', 'Division 1', 6121, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (95, 'Women''s Basketball', 'Division 1', 6121, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (136, 'Women''s Soccer', 'Division 1', 6121, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (174, 'Volleyball', 'Division 1', 6121, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (199, 'Women''s Track and Field', 'Division 1', 6877, 'https://questionnaire.acsathletics.com/Questionnaire/Questionnaire.aspx?q=37&s=533&o=40');
insert into sport (sportid, sportname, division, college_id, prospectform) values (85, 'Men''s Track and Field', 'Division 1', 6877, 'https://questionnaire.acsathletics.com/Questionnaire/Questionnaire.aspx?q=37&s=533&o=40');
insert into sport (sportid, sportname, division, college_id, prospectform) values (26, 'Baseball', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/questionnaire.asp?QID=7&oid=40&sid=521&hsid=&school_name=&city=&state=&whichpage=');
insert into sport (sportid, sportname, division, college_id, prospectform) values (96, 'Women''s Basketball', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/questionnaire.asp?QID=8&oid=40&sid=523&hsid=&school_name=&city=&state=&whichpage=');
insert into sport (sportid, sportname, division, college_id, prospectform) values (12, 'Men''s Basketball', 'Division 1', 6877, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (39, 'Men''s Cross Country', 'Division 1', 6877, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (110, 'Women''s Cross Country', 'Division 1', 6877, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (68, 'Football', 'Division 1', 6877, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (124, 'Women''s Golf', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=527');
insert into sport (sportid, sportname, division, college_id, prospectform) values (2, 'Men''s Golf', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=526');
insert into sport (sportid, sportname, division, college_id, prospectform) values (150, 'Softball', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/questionnaire.asp?QID=9&oid=40&sid=529&hsid=&school_name=&city=&state=&whichpage=');
insert into sport (sportid, sportname, division, college_id, prospectform) values (137, 'Women''s Soccer', 'Division 1', 6877, 'https://questionnaire.acsathletics.com/Questionnaire/Questionnaire.aspx?YyfngU7YszVN3VNSAfhno6pSTedgAe3XrzJAo53ULt%2fWFSvj0Ua2TBZ8FtlsbfGX');
insert into sport (sportid, sportname, division, college_id, prospectform) values (59, 'Men''s Tennis', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=531');
insert into sport (sportid, sportname, division, college_id, prospectform) values (165, 'Women''s Tennis', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=540');
insert into sport (sportid, sportname, division, college_id, prospectform) values (175, 'Volleyball', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=534');
insert into sport (sportid, sportname, division, college_id, prospectform) values (77, 'Wrestling', 'Division 1', 6877, 'https://secure.assistantcoach.net/colleges/athlete_webform.asp?oid=40&sid=535');
insert into sport (sportid, sportname, division, college_id, prospectform) values (27, 'Baseball', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=16');
insert into sport (sportid, sportname, division, college_id, prospectform) values (3, 'Men''s Golf', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=19');
insert into sport (sportid, sportname, division, college_id, prospectform) values (13, 'Men''s Basketball', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=15');
insert into sport (sportid, sportname, division, college_id, prospectform) values (50, 'Men''s Soccer', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=21');
insert into sport (sportid, sportname, division, college_id, prospectform) values (60, 'Men''s Tennis', 'Division 1', 6420, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (97, 'Women''s Basketball', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (111, 'Women''s Cross Country', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?iid=471&sportid=58');
insert into sport (sportid, sportname, division, college_id, prospectform) values (125, 'Women''s Golf', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=7');
insert into sport (sportid, sportname, division, college_id, prospectform) values (138, 'Women''s Soccer', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?iid=471&sportid=9');
insert into sport (sportid, sportname, division, college_id, prospectform) values (151, 'Softball', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=31');
insert into sport (sportid, sportname, division, college_id, prospectform) values (166, 'Women''s Tennis', 'Division 1', 6420, 'null');
insert into sport (sportid, sportname, division, college_id, prospectform) values (176, 'Volleyball', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?iid=471&sportid=58');
insert into sport (sportid, sportname, division, college_id, prospectform) values (189, 'Women''s Track and Field', 'Division 1', 6420, 'http://college.jumpforward.com/questionnaire.aspx?DB_OEM_ID=31400&iid=471&sportid=13');
insert into sport (sportid, sportname, division, college_id, prospectform) values (14, 'Men''s Basketball', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=7');
insert into sport (sportid, sportname, division, college_id, prospectform) values (40, 'Men''s Cross Country', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (67, 'Football', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=10');
insert into sport (sportid, sportname, division, college_id, prospectform) values (78, 'Wrestling', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=9');
insert into sport (sportid, sportname, division, college_id, prospectform) values (86, 'Men''s Track and Field', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (98, 'Women''s Basketball', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=6');
insert into sport (sportid, sportname, division, college_id, prospectform) values (112, 'Women''s Cross Country', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (126, 'Women''s Golf', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=11');
insert into sport (sportid, sportname, division, college_id, prospectform) values (152, 'Softball', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=5');
insert into sport (sportid, sportname, division, college_id, prospectform) values (177, 'Volleyball', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=4');
insert into sport (sportid, sportname, division, college_id, prospectform) values (190, 'Women''s Track and Field', 'Division 2', 6466, 'http://chadroneagles.com/sb_output.aspx?form=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (4, 'Men''s Golf', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=mgolf');
insert into sport (sportid, sportname, division, college_id, prospectform) values (15, 'Men''s Basketball', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=mbball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (28, 'Baseball', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=baseball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (41, 'Men''s Cross Country', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=mcross');
insert into sport (sportid, sportname, division, college_id, prospectform) values (61, 'Men''s Tennis', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=mten');
insert into sport (sportid, sportname, division, college_id, prospectform) values (70, 'Football', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=football');
insert into sport (sportid, sportname, division, college_id, prospectform) values (79, 'Wrestling', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wrestling');
insert into sport (sportid, sportname, division, college_id, prospectform) values (87, 'Men''s Track and Field', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=mtrack');
insert into sport (sportid, sportname, division, college_id, prospectform) values (99, 'Women''s Basketball', 'Division 2', 6467, 'https://secureq.scoutwareforms.net/q/unk_wbb/a77u1.html');
insert into sport (sportid, sportname, division, college_id, prospectform) values (113, 'Women''s Cross Country', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wcross');
insert into sport (sportid, sportname, division, college_id, prospectform) values (127, 'Women''s Golf', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wgolf');
insert into sport (sportid, sportname, division, college_id, prospectform) values (140, 'Women''s Soccer', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=soc');
insert into sport (sportid, sportname, division, college_id, prospectform) values (153, 'Softball', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=softball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (167, 'Women''s Tennis', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wten');
insert into sport (sportid, sportname, division, college_id, prospectform) values (178, 'Volleyball', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wvball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (191, 'Women''s Track and Field', 'Division 2', 6467, 'http://www.lopers.com/sb_output.aspx?form=4&path=wtrack');
insert into sport (sportid, sportname, division, college_id, prospectform) values (16, 'Men''s Basketball', 'Division 2', 6469, 'http://college.jumpforward.com/questionnaire.aspx?iid=496&sportid=15');
insert into sport (sportid, sportname, division, college_id, prospectform) values (29, 'Baseball', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/baseball.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (42, 'Men''s Cross Country', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/cross_country.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (69, 'Football', 'Division 2', 6469, 'https://www.frontrush.com/FR_Web_App/Player/PlayerSubmit.aspx?sid=NjM5NQ==-G4pkhQBNujU=&ptype=recruit');
insert into sport (sportid, sportname, division, college_id, prospectform) values (88, 'Men''s Track and Field', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/track.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (100, 'Women''s Basketball', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/basketball_women.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (114, 'Women''s Cross Country', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/cross_country.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (139, 'Women''s Soccer', 'Division 2', 6469, 'https://www.frontrush.com/FR_Web_App/Player/PlayerSubmit.aspx?sid=5389&ptype=recruit');
insert into sport (sportid, sportname, division, college_id, prospectform) values (154, 'Softball', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/softball.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (179, 'Volleyball', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/volleyball.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (192, 'Women''s Track and Field', 'Division 2', 6469, 'http://www.wsc.edu/admission/questionnaires/track.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (5, 'Men''s Golf', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=9');
insert into sport (sportid, sportname, division, college_id, prospectform) values (17, 'Men''s Basketball', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=5');
insert into sport (sportid, sportname, division, college_id, prospectform) values (30, 'Baseball', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=5');
insert into sport (sportid, sportname, division, college_id, prospectform) values (43, 'Men''s Cross Country', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=2');
insert into sport (sportid, sportname, division, college_id, prospectform) values (51, 'Men''s Soccer', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=7');
insert into sport (sportid, sportname, division, college_id, prospectform) values (62, 'Men''s Tennis', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=10');
insert into sport (sportid, sportname, division, college_id, prospectform) values (71, 'Football', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=6');
insert into sport (sportid, sportname, division, college_id, prospectform) values (89, 'Men''s Track and Field', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=2');
insert into sport (sportid, sportname, division, college_id, prospectform) values (101, 'Women''s Basketball', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=4');
insert into sport (sportid, sportname, division, college_id, prospectform) values (115, 'Women''s Cross Country', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=2');
insert into sport (sportid, sportname, division, college_id, prospectform) values (128, 'Women''s Golf', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=8');
insert into sport (sportid, sportname, division, college_id, prospectform) values (141, 'Women''s Soccer', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=7');
insert into sport (sportid, sportname, division, college_id, prospectform) values (155, 'Softball', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=11');
insert into sport (sportid, sportname, division, college_id, prospectform) values (168, 'Women''s Tennis', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?form=10');
insert into sport (sportid, sportname, division, college_id, prospectform) values (180, 'Volleyball', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=3');
insert into sport (sportid, sportname, division, college_id, prospectform) values (193, 'Women''s Track and Field', 'NAIA', 6470, 'http://nwusports.com/sb_output.aspx?frform=2');
insert into sport (sportid, sportname, division, college_id, prospectform) values (7, 'Men''s Golf', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (19, 'Men''s Basketball', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (32, 'Baseball', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (44, 'Men''s Cross Country', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (53, 'Men''s Soccer', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (63, 'Men''s Tennis', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (72, 'Football', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (80, 'Wrestling', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (90, 'Men''s Track and Field', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (103, 'Women''s Basketball', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (117, 'Women''s Cross Country', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (130, 'Women''s Golf', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (143, 'Women''s Soccer', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (157, 'Softball', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (169, 'Women''s Tennis', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (182, 'Volleyball', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (194, 'Women''s Track and Field', 'NAIA', 6116, 'https://ss2.cune.edu/AQU/apply/');
insert into sport (sportid, sportname, division, college_id, prospectform) values (8, 'Men''s Golf', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/7/Sports_Forms/Golf_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (20, 'Men''s Basketball', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/1/Sports_Forms/Mens_Basketball_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (33, 'Baseball', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/3/Sports_Forms/Baseball_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (45, 'Men''s Cross Country', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/5/Sports_Forms/Cross_CountryTrack_and_Field_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (54, 'Men''s Soccer', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/8/Sports_Forms/Soccer_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (64, 'Men''s Tennis', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/9/Sports_Forms/Tennis_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (73, 'Football', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/6/Sports_Forms/Football_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (81, 'Wrestling', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/13/Sports_Forms/Wrestling_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (91, 'Men''s Track and Field', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/11/Sports_Forms/Cross_CountryTrack_and_Field_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (104, 'Women''s Basketball', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/2/Sports_Forms/Womens_Basketball_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (118, 'Women''s Cross Country', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/16/Sports_Forms/Cross_CountryTrack_and_Field_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (131, 'Women''s Golf', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/17/Sports_Forms/Golf_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (144, 'Women''s Soccer', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/18/Sports_Forms/Soccer_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (158, 'Softball', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/14/Sports_Forms/Softball_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (170, 'Women''s Tennis', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/19/Sports_Forms/Tennis_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (183, 'Volleyball', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/22/Sports_Forms/Volleyball_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (195, 'Women''s Track and Field', 'NAIA', 6165, 'http://www.doaneathletics.com/f/0/16/Sports_Forms/Cross_CountryTrack_and_Field_Form.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (9, 'Men''s Golf', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (21, 'Men''s Basketball', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (34, 'Baseball', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (46, 'Men''s Cross Country', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (55, 'Men''s Soccer', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/7.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (65, 'Men''s Tennis', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (74, 'Football', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/5.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (82, 'Wrestling', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/19.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (92, 'Men''s Track and Field', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (10, 'Men''s Golf', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=16');
insert into sport (sportid, sportname, division, college_id, prospectform) values (22, 'Men''s Basketball', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=9');
insert into sport (sportid, sportname, division, college_id, prospectform) values (23, 'Men''s Basketball', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=mbball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (24, 'Men''s Basketball', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/1.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (35, 'Baseball', 'NAIA', 6406, 'https://www.frontrush.com/FR_Web_App/Player/PlayerSubmit.aspx?sid=OTY0NA==-viOpmfKXR+I=&ptype=recruit');
insert into sport (sportid, sportname, division, college_id, prospectform) values (36, 'Baseball', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=baseball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (37, 'Baseball', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/3.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (47, 'Men''s Cross Country', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=12');
insert into sport (sportid, sportname, division, college_id, prospectform) values (48, 'Men''s Cross Country', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (56, 'Men''s Soccer', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=18');
insert into sport (sportid, sportname, division, college_id, prospectform) values (57, 'Men''s Soccer', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/5.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (66, 'Men''s Tennis', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=13');
insert into sport (sportid, sportname, division, college_id, prospectform) values (75, 'Football', 'NAIA', 6406, 'https://www.frontrush.com/FR_Web_App/Player/PlayerSubmit.aspx?sid=6189&ptype=recruit');
insert into sport (sportid, sportname, division, college_id, prospectform) values (76, 'Football', 'NAIA', 6468, 'http://pscbobcats.com/sports/2013/1/4/Football-Recruit.aspx?path=football');
insert into sport (sportid, sportname, division, college_id, prospectform) values (83, 'Wrestling', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=22');
insert into sport (sportid, sportname, division, college_id, prospectform) values (84, 'Wrestling', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/8.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (93, 'Men''s Track and Field', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=24');
insert into sport (sportid, sportname, division, college_id, prospectform) values (94, 'Men''s Track and Field', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/6.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (105, 'Women''s Basketball', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/2.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (106, 'Women''s Basketball', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=10');
insert into sport (sportid, sportname, division, college_id, prospectform) values (107, 'Women''s Basketball', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=wbball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (108, 'Women''s Basketball', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/2.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (102, 'Women''s Basketball', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/1.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (119, 'Women''s Cross Country', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (120, 'Women''s Cross Country', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=12');
insert into sport (sportid, sportname, division, college_id, prospectform) values (121, 'Women''s Cross Country', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=wcross');
insert into sport (sportid, sportname, division, college_id, prospectform) values (122, 'Women''s Cross Country', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/10.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (116, 'Women''s Cross Country', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/3.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (132, 'Women''s Golf', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (133, 'Women''s Golf', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=17');
insert into sport (sportid, sportname, division, college_id, prospectform) values (134, 'Women''s Golf', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=wgolf');
insert into sport (sportid, sportname, division, college_id, prospectform) values (129, 'Women''s Golf', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (145, 'Women''s Soccer', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/15.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (146, 'Women''s Soccer', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=19');
insert into sport (sportid, sportname, division, college_id, prospectform) values (147, 'Women''s Soccer', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/5.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (148, 'Women''s Soccer', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/11.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (159, 'Softball', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (160, 'Softball', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=20');
insert into sport (sportid, sportname, division, college_id, prospectform) values (161, 'Softball', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=softball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (162, 'Softball', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/2.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (163, 'Softball', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/9.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (171, 'Women''s Tennis', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruiting.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (172, 'Women''s Tennis', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=13');
insert into sport (sportid, sportname, division, college_id, prospectform) values (173, 'Women''s Tennis', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/9.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (196, 'Women''s Track and Field', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/4.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (197, 'Women''s Track and Field', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=24');
insert into sport (sportid, sportname, division, college_id, prospectform) values (198, 'Women''s Track and Field', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/12.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (184, 'Volleyball', 'NAIA', 6270, 'http://www.hastingsbroncos.com/recruitingFR/19.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (185, 'Volleyball', 'NAIA', 6406, 'http://www.midlandathletics.com/SIDHelp.php?action=form&parameters=15');
insert into sport (sportid, sportname, division, college_id, prospectform) values (186, 'Volleyball', 'NAIA', 6468, 'http://pscbobcats.com/sb_output.aspx?form=3&path=wvball');
insert into sport (sportid, sportname, division, college_id, prospectform) values (187, 'Volleyball', 'NAIA', 6106, 'http://www.csmflames.com/recruiting/0/7.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (188, 'Volleyball', 'NAIA', 6984, 'http://www.ycpanthers.com/recruiting/0/14.php');
insert into sport (sportid, sportname, division, college_id, prospectform) values (200, 'Men''s Basketball', 'Division 3', 3965, 'http://ephsports.williams.edu/sports/mbkb/recruitForm');
insert into sport (sportid, sportname, division, college_id, prospectform) values (201, 'Men''s Golf', 'Division 3', 3965, 'http://ephsports.williams.edu/sports/mgolf/prospectiveathlete');
insert into sport (sportid, sportname, division, college_id, prospectform) values (202, 'Baseball', 'Division 3', 3965, 'http://ephsports.williams.edu/sports/bsb/prospectiveathlete');




# --- !Downs

delete from college;
delete from sport;